# Generated by Django 4.2.16 on 2024-11-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islam', '0002_rename_name_surah_namear_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameAr', models.CharField(max_length=255)),
                ('nameEn', models.CharField(max_length=255)),
                ('translation', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('total_ayat', models.IntegerField()),
            ],
        ),
    ]
