# Generated by Django 4.2.16 on 2024-11-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islam', '0004_delete_juz_rename_namear_surah_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surah',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
