# Generated by Django 4.2.16 on 2024-11-27 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('islam', '0005_alter_surah_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surah1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('verse', models.JSONField()),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Juz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=10)),
                ('start_verse', models.CharField(max_length=50)),
                ('end_verse', models.CharField(max_length=50)),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juz', to='islam.surah')),
            ],
        ),
    ]
