# Generated by Django 4.2.16 on 2024-11-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islam', '0008_remove_surah1_verse_alter_juz_end_verse_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verse',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='verse',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='juz',
            name='index',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='verse',
            name='verse_ar',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='verse',
            name='verse_en',
            field=models.TextField(null=True),
        ),
    ]
