# Generated by Django 4.2.16 on 2024-12-07 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('islam', '0011_hadith'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arabic_title', models.CharField(max_length=255)),
                ('arabic_author', models.CharField(max_length=255)),
                ('arabic_introduction', models.TextField()),
                ('english_title', models.CharField(max_length=255)),
                ('english_author', models.CharField(max_length=255)),
                ('english_introduction', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='hadith',
            name='arabic_author',
        ),
        migrations.RemoveField(
            model_name='hadith',
            name='arabic_introduction',
        ),
        migrations.RemoveField(
            model_name='hadith',
            name='arabic_title',
        ),
        migrations.RemoveField(
            model_name='hadith',
            name='english_author',
        ),
        migrations.RemoveField(
            model_name='hadith',
            name='english_introduction',
        ),
        migrations.RemoveField(
            model_name='hadith',
            name='english_title',
        ),
        migrations.RemoveField(
            model_name='hadith',
            name='metadata_length',
        ),
        migrations.AddField(
            model_name='hadith',
            name='metadata',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hadiths', to='islam.metadata'),
        ),
    ]
