# Generated by Django 4.2.16 on 2024-12-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islam', '0012_metadata_remove_hadith_arabic_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='length',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
