# Generated by Django 4.2.16 on 2024-12-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islam', '0013_metadata_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
