# Generated by Django 4.2.16 on 2024-12-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islam', '0014_alter_metadata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
