# Generated by Django 4.2.16 on 2024-12-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islam', '0015_alter_metadata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hadith',
            name='english_narrator',
            field=models.CharField(max_length=2555),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='arabic_author',
            field=models.CharField(max_length=2555),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='arabic_title',
            field=models.CharField(max_length=2555),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='english_author',
            field=models.CharField(max_length=2555),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='english_title',
            field=models.CharField(max_length=2555),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='length',
            field=models.CharField(max_length=2555, null=True),
        ),
    ]
