# Generated by Django 4.2.18 on 2025-02-04 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('islam', '0019_duacard_eventcard_hadithcard_holyplace_versecard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holyplace',
            name='image',
        ),
        migrations.AddField(
            model_name='holyplace',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='holy_places/'),
        ),
        migrations.CreateModel(
            name='HolyPlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='holy_places/')),
                ('holy_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='islam.holyplace')),
            ],
        ),
    ]
