# Generated by Django 5.1 on 2024-10-08 03:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllCategoryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
                ('route', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BottomNavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disable_icon', models.CharField(blank=True, max_length=255, null=True)),
                ('anable_icon', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(max_length=255)),
                ('isSelected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DonationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField(max_length=500)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('project_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('position', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('days', models.TextField()),
                ('friday', models.TextField()),
            ],
        ),
    ]
