# Generated by Django 5.1 on 2024-10-08 04:45

import data.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationmodel',
            name='category',
            field=models.ForeignKey(default=data.models.get_default_category, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='data.category'),
        ),
    ]
