# Generated by Django 4.2.16 on 2024-10-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_donationmodel_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='donationmodel',
            name='donation_options',
            field=models.ManyToManyField(blank=True, to='data.donationoption'),
        ),
    ]
