# Generated by Django 4.2.16 on 2024-11-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_donationhistory_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationhistory',
            name='donor_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
