# Generated by Django 4.2.16 on 2024-11-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_rename_image_donationhistory_payment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationhistory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='payment_images/'),
        ),
    ]
