# Generated by Django 4.2.16 on 2024-11-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_donationhistory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationhistory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
    ]
