# Generated by Django 4.2.16 on 2024-11-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_alter_donationhistory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationhistory',
            name='is_sadqah',
            field=models.BooleanField(default=False, verbose_name='Sadqah'),
        ),
        migrations.AddField(
            model_name='donationhistory',
            name='is_zakat',
            field=models.BooleanField(default=False, verbose_name='Zakat'),
        ),
    ]
