# Generated by Django 4.2.16 on 2024-12-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_videopost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='video',
            field=models.FileField(upload_to='videos/%y'),
        ),
    ]
