# Generated by Django 4.2.16 on 2024-12-11 15:27

import data.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_alter_videopost_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySelect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='donationmodel',
            name='categoryselect',
            field=models.ForeignKey(default=data.models.get_default_category, on_delete=django.db.models.deletion.CASCADE, related_name='donationsselect', to='data.categoryselect'),
        ),
    ]
