# Generated by Django 4.2.16 on 2024-12-11 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_categoryselect_donationmodel_categoryselect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationmodel',
            name='categoryselect',
        ),
    ]
