# Generated by Django 4.2.16 on 2024-12-11 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_remove_donationmodel_categoryselect'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategorySelect',
        ),
    ]
