# Generated by Django 4.2.16 on 2024-12-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_rename_categoryselect_donationmodel_category_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcategorymodel',
            name='category_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
