# Generated by Django 4.2.16 on 2024-12-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_donationhistory_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/')),
                ('text1', models.CharField(max_length=255)),
                ('text2', models.CharField(max_length=255)),
                ('detail', models.TextField()),
            ],
        ),
    ]
