# Generated by Django 4.2.16 on 2024-12-22 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0025_donationoptionscategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DonationOption',
        ),
        migrations.DeleteModel(
            name='DonationOptionsCategory',
        ),
    ]
