# Generated by Django 4.2.16 on 2024-12-22 21:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0026_delete_donationoption_delete_donationoptionscategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='individual_category/')),
                ('route', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StaticCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Static Category/')),
                ('route', models.CharField(max_length=255)),
            ],
        ),
    ]
