# Generated by Django 4.2.16 on 2024-12-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0027_individualcategory_staticcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationhistory',
            name='age',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='donationhistory',
            name='gender',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='donationhistory',
            name='heading_category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='donationhistory',
            name='select_category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='staticcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Static_Category/'),
        ),
    ]
