# Generated by Django 4.2.16 on 2024-12-23 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0028_donationhistory_age_donationhistory_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationhistory',
            name='age',
        ),
        migrations.RemoveField(
            model_name='donationhistory',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='donationhistory',
            name='heading_category',
        ),
        migrations.RemoveField(
            model_name='donationhistory',
            name='select_category',
        ),
    ]
