# Generated by Django 4.2.16 on 2024-12-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0029_remove_donationhistory_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationhistory',
            name='age',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='donationhistory',
            name='gender',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='donationhistory',
            name='heading_category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='donationhistory',
            name='select_category',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
