# Generated by Django 4.2.16 on 2024-12-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0031_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
