# Generated by Django 4.2.16 on 2024-12-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0032_alter_videopost_description_alter_videopost_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationhistory',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
