# Generated by Django 4.2.16 on 2025-01-04 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0037_donation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donation',
            new_name='IndividualDonorRequest',
        ),
    ]
