# Generated by Django 4.2.16 on 2025-01-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0038_rename_donation_individualdonorrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualdonorrequest',
            name='optional',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
