# Generated by Django 4.2.16 on 2025-01-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0039_individualdonorrequest_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
