# Generated by Django 4.2.16 on 2025-01-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0041_donationmodel_title_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationmodel',
            name='project_id',
            field=models.IntegerField(null=True),
        ),
    ]
