# Generated by Django 4.2.18 on 2025-01-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0042_donationmodel_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationmodel',
            name='total_beneficieries',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
