# Generated by Django 4.2.18 on 2025-02-01 21:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0043_donationmodel_total_beneficieries'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='donation_images/')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='data.donationmodel')),
            ],
        ),
    ]
