# Generated by Django 4.2.18 on 2025-02-01 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0044_donationimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationimage',
            old_name='image',
            new_name='images',
        ),
    ]
